; M5Stack Core2 — nó IoT Air Quality (versão com display + NTP/RTC)
; Projeto separado do firmware/ (ESP32-C3) de proposito: o codigo diverge
; muito por causa de display/touch/RTC. Pipeline (MQTT/identidade) sera reusado.

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-58640316871
monitor_port = /dev/cu.usbserial-58640316871
lib_deps =
	m5stack/M5Unified@^0.2.0
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.12.0
